"use client";

import Link from "next/link";
import { ChevronLeft, ChevronRight, Landmark, Search, WalletCards } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

import { ConfirmDialog } from "@/components/admin/confirm-dialog";
import { EmptyState, ErrorState } from "@/components/shared/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatCurrency, formatDateTime } from "@/lib/utils/format";

type Wallet = { currency: string; availableMinor: string; heldMinor: string; lifetimeCreditMinor: string; lifetimeDebitMinor: string; lifetimeEarningsMinor: string; lifetimeWithdrawalsMinor: string };
type Transaction = { id: string; type: string; direction: "CREDIT" | "DEBIT"; amountMinor: string; resultingAvailableMinor: string; resultingHeldMinor: string; description: string; createdAt: string };
type WalletData = { wallet: Wallet; transactions: Transaction[]; pagination: { total: number; page: number; limit: number; totalPages: number }; member?: { memberNumber: string; name: string; status: string }; capabilities?: { adjust: boolean } };
type WalletAccount = { id: string; memberNumber: string; name: string; status: string; currency: string; availableMinor: string; heldMinor: string; lifetimeEarningsMinor: string; lifetimeWithdrawalsMinor: string; lastTransaction: { type: string; createdAt: string } | null };
type WalletAccountPage = { items: WalletAccount[]; total: number; page: number; limit: number; totalPages: number };
type Adjustment = { direction: "CREDIT" | "DEBIT"; amount: string; reason: string; idempotencyKey: string };
type ApiResponse<T> = { success: true; data: T } | { success: false; error?: { message?: string } };

async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init); const payload = await response.json() as ApiResponse<T>;
  if (!response.ok || !payload.success) throw new Error(!payload.success ? payload.error?.message ?? "Request failed." : "Request failed.");
  return payload.data;
}

function Summary({ wallet }: { wallet: Wallet }) {
  const entries = [["Available balance", wallet.availableMinor, "Spendable funds"], ["Reserved balance", wallet.heldMinor, "Held for withdrawals"], ["Lifetime credits", wallet.lifetimeCreditMinor, "All ledger credits"], ["Lifetime debits", wallet.lifetimeDebitMinor, "All ledger debits"], ["Lifetime earnings", wallet.lifetimeEarningsMinor, "Commission earnings"], ["Lifetime withdrawals", wallet.lifetimeWithdrawalsMinor, "Completed withdrawals"]];
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{entries.map(([label, amount, note]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight">{formatCurrency(amount, wallet.currency)}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></CardContent></Card>)}</div>;
}

function Pager({ total, page, totalPages, onPage }: { total: number; page: number; totalPages: number; onPage: (page: number) => void }) { return <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-muted-foreground"><span>{total} records · Page {page} of {totalPages}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft className="size-4" />Previous</Button><Button size="sm" variant="outline" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next<ChevronRight className="size-4" /></Button></div></div>; }

function TransactionHistory({ data, onChange }: { data: WalletData; onChange: (type: string, direction: string, page: number) => void }) {
  const [type, setType] = useState(""); const [direction, setDirection] = useState(""); const update = (nextType: string, nextDirection: string, page = 1) => { setType(nextType); setDirection(nextDirection); onChange(nextType, nextDirection, page); };
  return <Card><CardHeader className="gap-4 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Recent ledger transactions</CardTitle><CardDescription>Immutable entries; amounts and balance snapshots cannot be edited.</CardDescription></div><div className="grid grid-cols-2 gap-2"><select aria-label="Filter wallet transaction type" value={type} onChange={(event) => update(event.target.value, direction)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">All types</option><option value="DIRECT_COMMISSION">Direct commission</option><option value="LEVEL_COMMISSION">Level commission</option><option value="WITHDRAWAL_RESERVATION">Withdrawal reservation</option><option value="WITHDRAWAL_RELEASE">Withdrawal release</option><option value="WITHDRAWAL">Withdrawal settlement</option><option value="ADMIN_CREDIT">Admin credit</option><option value="ADMIN_DEBIT">Admin debit</option></select><select aria-label="Filter wallet transaction direction" value={direction} onChange={(event) => update(type, event.target.value)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">All directions</option><option value="CREDIT">Credits</option><option value="DEBIT">Debits</option></select></div></CardHeader><CardContent>{data.transactions.length ? <><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Entry</TableHead><TableHead>Direction</TableHead><TableHead>Amount</TableHead><TableHead>Balance after</TableHead><TableHead>Time</TableHead></TableRow></TableHeader><TableBody>{data.transactions.map((entry) => <TableRow key={entry.id}><TableCell><p className="font-medium">{entry.type.replaceAll("_", " ")}</p><p className="max-w-xs truncate text-xs text-muted-foreground" title={entry.description}>{entry.description}</p></TableCell><TableCell><Badge variant={entry.direction === "CREDIT" ? "success" : "warning"}>{entry.direction}</Badge></TableCell><TableCell className={entry.direction === "CREDIT" ? "font-semibold text-emerald-700" : "font-semibold text-foreground"}>{entry.direction === "CREDIT" ? "+" : "-"}{formatCurrency(entry.amountMinor, data.wallet.currency)}</TableCell><TableCell>{formatCurrency(entry.resultingAvailableMinor, data.wallet.currency)}</TableCell><TableCell className="whitespace-nowrap text-sm text-muted-foreground">{formatDateTime(entry.createdAt)}</TableCell></TableRow>)}</TableBody></Table></div><Pager total={data.pagination.total} page={data.pagination.page} totalPages={data.pagination.totalPages} onPage={(page) => onChange(type, direction, page)} /></> : <EmptyState title="No wallet entries yet" description="Commission credits and other wallet activity will appear here when posted." />}</CardContent></Card>;
}

function WalletContent({ endpoint }: { endpoint: string }) {
  const [data, setData] = useState<WalletData | null>(null); const [error, setError] = useState(false); const [loading, setLoading] = useState(true); const [adjusting, setAdjusting] = useState(false); const [pending, setPending] = useState<Adjustment | null>(null); const adjustmentForm = useRef<HTMLFormElement>(null); const adjustmentInFlight = useRef(false);
  const load = useCallback(async (type = "", direction = "", page = 1) => { setLoading(true); setError(false); const query = new URLSearchParams({ page: String(page) }); if (type) query.set("type", type); if (direction) query.set("direction", direction); try { setData(await request<WalletData>(`${endpoint}?${query}`)); } catch { setError(true); } finally { setLoading(false); } }, [endpoint]);
  useEffect(() => { void Promise.resolve().then(() => load()); }, [load]);
  const postAdjustment = async () => { if (!pending || adjustmentInFlight.current) return; adjustmentInFlight.current = true; setAdjusting(true); try { await request(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(pending) }); toast.success("Wallet adjustment posted to the immutable ledger."); adjustmentForm.current?.reset(); setPending(null); await load(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Could not post wallet adjustment."); } finally { adjustmentInFlight.current = false; setAdjusting(false); } };
  if (loading && !data) return <div className="space-y-5"><Skeleton className="h-32" /><Skeleton className="h-80" /></div>;
  if (error || !data) return <ErrorState title="Wallet data could not be loaded" description="Please refresh and try again." />;
  return <div className="space-y-6">{data.member ? <Card><CardContent className="flex items-center gap-3 p-5"><Landmark className="size-5 text-primary" /><div><p className="font-semibold">{data.member.name} <span className="font-normal text-muted-foreground">· {data.member.memberNumber}</span></p><p className="text-sm text-muted-foreground">Member status: {data.member.status}</p></div></CardContent></Card> : null}<Summary wallet={data.wallet} />{data.capabilities?.adjust ? <Card><CardHeader><CardTitle>Manual adjustment</CardTitle><CardDescription>Credit or debit through the immutable ledger. The balance itself is never set directly.</CardDescription></CardHeader><CardContent><form ref={adjustmentForm} className="grid gap-3 md:grid-cols-[160px_1fr_2fr_auto]" onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); setPending({ direction: String(values.get("direction")) as Adjustment["direction"], amount: String(values.get("amount") ?? ""), reason: String(values.get("reason") ?? ""), idempotencyKey: crypto.randomUUID() }); }}><select name="direction" aria-label="Adjustment direction" className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="CREDIT">Credit</option><option value="DEBIT">Debit</option></select><Input name="amount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" placeholder="Amount, e.g. 250.00" required /><Input name="reason" placeholder="Reason, at least 10 characters" minLength={10} maxLength={500} required /><Button type="submit" disabled={adjusting || Boolean(pending)}><WalletCards className="size-4" />Post adjustment</Button></form></CardContent></Card> : null}<TransactionHistory data={data} onChange={(type, direction, page) => void load(type, direction, page)} /><ConfirmDialog open={Boolean(pending)} onOpenChange={(open) => { if (!open && !adjusting) setPending(null); }} title={`${pending?.direction === "DEBIT" ? "Debit" : "Credit"} wallet?`} description={pending ? `${pending.direction === "DEBIT" ? "Debit" : "Credit"} ${pending.amount} with the recorded reason. This creates an immutable ledger and audit entry.` : ""} confirmLabel={pending?.direction === "DEBIT" ? "Confirm debit" : "Confirm credit"} destructive={pending?.direction === "DEBIT"} confirming={adjusting} onConfirm={postAdjustment} /></div>;
}

function WalletAccountList() {
  const [items, setItems] = useState<WalletAccount[] | null>(null); const [pagination, setPagination] = useState({ total: 0, page: 1, limit: 20, totalPages: 1 }); const [error, setError] = useState(false); const [q, setQ] = useState(""); const [minBalance, setMinBalance] = useState(""); const [maxBalance, setMaxBalance] = useState(""); const [applied, setApplied] = useState({ q: "", minBalance: "", maxBalance: "" });
  const load = useCallback(async (page = 1) => { setError(false); setItems(null); const params = new URLSearchParams({ page: String(page), limit: "20", ...(applied.q ? { q: applied.q } : {}), ...(applied.minBalance ? { minBalance: applied.minBalance } : {}), ...(applied.maxBalance ? { maxBalance: applied.maxBalance } : {}) }); try { const data = await request<WalletAccountPage>(`/api/v1/admin/wallets?${params}`); setItems(data.items); setPagination({ total: data.total, page: data.page, limit: data.limit, totalPages: data.totalPages }); } catch { setError(true); } }, [applied]);
  useEffect(() => { void Promise.resolve().then(() => load(1)); }, [load]);
  if (error) return <ErrorState title="Wallet accounts could not be loaded" description="Refresh the page or check your wallet access permission." />;
  return <Card><CardHeader><CardTitle>Wallet accounts</CardTitle><CardDescription>Account summaries are derived from the immutable ledger. Open a member to inspect the full ledger and permitted actions.</CardDescription></CardHeader><CardContent><form className="grid gap-2 md:grid-cols-[2fr_1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); setApplied({ q: q.trim(), minBalance, maxBalance }); }}><Input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Member ID, name, email, or referral code" aria-label="Search wallets" /><Input value={minBalance} onChange={(event) => setMinBalance(event.target.value)} inputMode="decimal" placeholder="Minimum balance" aria-label="Minimum balance" /><Input value={maxBalance} onChange={(event) => setMaxBalance(event.target.value)} inputMode="decimal" placeholder="Maximum balance" aria-label="Maximum balance" /><Button type="submit"><Search className="size-4" />Search</Button></form>{!items ? <Skeleton className="mt-4 h-64" /> : items.length ? <><div className="mt-4 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Member</TableHead><TableHead>Member ID</TableHead><TableHead>Available balance</TableHead><TableHead>Reserved</TableHead><TableHead>Lifetime earnings</TableHead><TableHead>Lifetime withdrawn</TableHead><TableHead>Last transaction</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Open</span></TableHead></TableRow></TableHeader><TableBody>{items.map((wallet) => <TableRow key={wallet.id}><TableCell className="font-medium">{wallet.name}</TableCell><TableCell className="font-mono text-xs">{wallet.memberNumber}</TableCell><TableCell>{formatCurrency(wallet.availableMinor, wallet.currency)}</TableCell><TableCell>{formatCurrency(wallet.heldMinor, wallet.currency)}</TableCell><TableCell>{formatCurrency(wallet.lifetimeEarningsMinor, wallet.currency)}</TableCell><TableCell>{formatCurrency(wallet.lifetimeWithdrawalsMinor, wallet.currency)}</TableCell>{wallet.lastTransaction ? <TableCell><p>{wallet.lastTransaction.type.replaceAll("_", " ")}</p><p className="text-xs text-muted-foreground">{formatDateTime(wallet.lastTransaction.createdAt)}</p></TableCell> : <TableCell className="text-muted-foreground">No activity</TableCell>}<TableCell><Badge variant={wallet.status === "ACTIVE" ? "success" : "warning"}>{wallet.status}</Badge></TableCell><TableCell><Button asChild size="sm" variant="outline"><Link href={`/admin/wallet/${encodeURIComponent(wallet.memberNumber)}`}>Open</Link></Button></TableCell></TableRow>)}</TableBody></Table></div><Pager total={pagination.total} page={pagination.page} totalPages={pagination.totalPages} onPage={(page) => void load(page)} /></> : <EmptyState title="No wallet accounts found" description="Try clearing the search or expanding the balance range." />}</CardContent></Card>;
}

export function MemberWalletPanel() { return <WalletContent endpoint="/api/v1/wallet/me" />; }
export function AdminWalletDetailPanel({ memberNumber }: { memberNumber: string }) { return <WalletContent endpoint={`/api/v1/admin/wallets/${encodeURIComponent(memberNumber)}`} />; }
export function AdminWalletPanel() { return <WalletAccountList />; }
