"use client";

import Link from "next/link";
import { ArrowLeft, Edit3, Network, ShieldAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { ConfirmDialog } from "@/components/admin/confirm-dialog";
import { StatCard } from "@/components/admin/stat-card";
import { StatusBadge } from "@/components/admin/status-badge";
import { EmptyState, ErrorState } from "@/components/shared/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency, formatDateTime } from "@/lib/utils/format";

type Detail = { canManage: boolean; access: { network: boolean; financials: boolean; orders: boolean; audit: boolean }; overview: { memberNumber: string; referralCode: string; name: string; email: string; phone: string; status: string; accountStatus: string; joinedAt: string; sponsor: { memberNumber: string; name: string } | null; directReferrals: number; teamCount: number; walletBalanceMinor?: string; currency?: string; lifetimeEarningsMinor?: string; withdrawalSummary?: { total: number; pending: { count: number; amountMinor: string }; completed: { count: number; amountMinor: string } }; orderSummary?: { count: number; totalMinor: string } }; profile: Profile; sponsorNetwork: { sponsor: { memberNumber: string; name: string; status: string } | null; directReferrals: Array<{ id: string; memberNumber: string; name: string; status: string; joinedAt: string }>; uplineMemberIds: string[] }; wallet: { currency: string; availableMinor: string; heldMinor: string; lifetimeEarningsMinor: string; lifetimeWithdrawalsMinor: string } | null; withdrawals: Array<{ id: string; amountMinor: string; currency: string; status: string; createdAt: string }>; orders: Array<{ id: string; orderNumber: string; totalMinor: string; currency: string; status: string; paymentStatus: string; createdAt: string }>; commissions: Array<{ id: string; type: string; level: number | null; amountMinor: string; currency: string; status: string; createdAt: string }>; activity: Array<{ id: string; action: string; resourceType: string; createdAt: string }> };
type Profile = { firstName: string; lastName: string; phone: string; alternatePhone: string; address: { line1?: string; line2?: string; city?: string; state?: string; postalCode?: string; country?: string } | null };
type ApiResponse = { success: true; data: Detail } | { success: false; error?: { message?: string } };
const tabs = ["Overview", "Profile", "Sponsor & Network", "Genealogy", "Commissions", "Wallet", "Withdrawals", "Orders", "Activity"] as const;
type Tab = (typeof tabs)[number]; type StatusAction = "ACTIVE" | "SUSPENDED" | "DISABLED";

export function MemberDetail({ id }: { id: string }) {
  const [data, setData] = useState<Detail | null>(null); const [tab, setTab] = useState<Tab>("Overview"); const [failed, setFailed] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false); const [statusTarget, setStatusTarget] = useState<StatusAction | null>(null); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { try { const response = await fetch(`/api/v1/admin/members/${id}`, { cache: "no-store" }); const payload = await response.json() as ApiResponse; if (!response.ok || !payload.success) throw new Error(payload.success ? "" : payload.error?.message); setData(payload.data); setFailed(false); } catch { setFailed(true); } }, [id]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const mutate = async (kind: "profile" | "status", payload: unknown) => { setSaving(true); setMessage(null); try { const response = await fetch(`/api/v1/admin/members/${id}`, { method: kind === "profile" ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { success?: boolean; error?: { message?: string } }; if (!response.ok || !body.success) throw new Error(body.error?.message ?? "The update could not be saved."); await load(); setMessage("Member record updated successfully."); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "The update could not be saved."); return false; } finally { setSaving(false); } };
  if (!data && !failed) return <Skeleton className="h-[36rem]" />;
  if (!data || failed) return <ErrorState title="Member detail could not be loaded" description="The member may not exist, or you may not have permission to view it." />;
  const statusLabel = statusTarget === "ACTIVE" ? "Activate member" : statusTarget === "SUSPENDED" ? "Suspend member" : "Disable member";
  const section = () => {
    if (tab === "Overview") return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Member ID" value={data.overview.memberNumber} /><Info label="Email" value={data.overview.email} /><Info label="Phone" value={data.overview.phone || "—"} /><Info label="Referral code" value={data.overview.referralCode} /><Info label="Join date" value={formatDateTime(data.overview.joinedAt)} />{data.access.network ? <Info label="Sponsor" value={data.overview.sponsor ? `${data.overview.sponsor.name} · ${data.overview.sponsor.memberNumber}` : "No sponsor"} /> : null}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.access.network ? <><StatCard label="Direct referrals" value={data.overview.directReferrals} /><StatCard label="Team count" value={data.overview.teamCount} /></> : null}{data.access.financials && data.overview.withdrawalSummary && data.overview.walletBalanceMinor && data.overview.lifetimeEarningsMinor ? <><StatCard label="Wallet balance" value={formatCurrency(data.overview.walletBalanceMinor, data.overview.currency ?? "INR")} /><StatCard label="Lifetime earnings" value={formatCurrency(data.overview.lifetimeEarningsMinor, data.overview.currency ?? "INR")} /><StatCard label="Withdrawals" value={data.overview.withdrawalSummary.total} detail={`${data.overview.withdrawalSummary.pending.count} pending`} /><StatCard label="Completed withdrawals" value={data.overview.withdrawalSummary.completed.count} /></> : null}{data.access.orders && data.overview.orderSummary ? <><StatCard label="Orders" value={data.overview.orderSummary.count} /><StatCard label="Order total" value={formatCurrency(data.overview.orderSummary.totalMinor, data.overview.currency ?? "INR")} /></> : null}</div></>;
    if (tab === "Profile") return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Info label="Name" value={data.overview.name} /><Info label="Phone" value={data.profile.phone || "—"} /><Info label="Alternate phone" value={data.profile.alternatePhone || "—"} /><Info label="Address" value={data.profile.address ? Object.values(data.profile.address).filter(Boolean).join(", ") : "—"} /></div>{data.canManage ? <Button onClick={() => setProfileOpen(true)}><Edit3 className="size-4" />Edit allowed profile fields</Button> : null}<p className="text-sm text-muted-foreground">Financial balances, commission history, referrals, and roles cannot be edited here.</p></div>;
    if (tab === "Sponsor & Network") return <div className="space-y-5">{data.sponsorNetwork.sponsor ? <Info label="Direct sponsor" value={`${data.sponsorNetwork.sponsor.name} · ${data.sponsorNetwork.sponsor.memberNumber}`} /> : <EmptyState title="No sponsor" description="This member was registered without a sponsor." />}<Rows rows={data.sponsorNetwork.directReferrals.map((row) => [row.name, row.memberNumber, row.status, formatDateTime(row.joinedAt)])} emptyTitle="No direct referrals" /></div>;
    if (tab === "Genealogy") return <div className="grid gap-4 sm:grid-cols-2"><Info label="Upline depth" value={String(data.sponsorNetwork.uplineMemberIds.length)} /><Info label="Direct referrals" value={String(data.overview.directReferrals)} /><Button asChild><Link href={`/admin/genealogy?root=${encodeURIComponent(data.overview.memberNumber)}`}><Network className="size-4" />Open genealogy</Link></Button></div>;
    if (tab === "Commissions") return <Rows rows={data.commissions.map((row) => [`${row.type}${row.level ? ` · Level ${row.level}` : ""}`, formatCurrency(row.amountMinor, row.currency), row.status, formatDateTime(row.createdAt)])} emptyTitle="No commissions" />;
    if (tab === "Wallet") return data.wallet ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Available" value={formatCurrency(data.wallet.availableMinor, data.wallet.currency)} /><Info label="Held" value={formatCurrency(data.wallet.heldMinor, data.wallet.currency)} /><Info label="Lifetime earnings" value={formatCurrency(data.wallet.lifetimeEarningsMinor, data.wallet.currency)} /><Info label="Lifetime withdrawals" value={formatCurrency(data.wallet.lifetimeWithdrawalsMinor, data.wallet.currency)} /><Button asChild><Link href={`/admin/wallet?member=${encodeURIComponent(data.overview.memberNumber)}`}>Open wallet workflow</Link></Button></div> : <EmptyState title="No wallet" description="A wallet has not been initialized for this member." />;
    if (tab === "Withdrawals") return <Rows rows={data.withdrawals.map((row) => [formatCurrency(row.amountMinor, row.currency), row.status, formatDateTime(row.createdAt)])} emptyTitle="No withdrawals" />;
    if (tab === "Orders") return <Rows rows={data.orders.map((row) => [row.orderNumber, formatCurrency(row.totalMinor, row.currency), `${row.status} · ${row.paymentStatus}`, formatDateTime(row.createdAt)])} emptyTitle="No orders" />;
    return <Rows rows={data.activity.map((row) => [row.action.replaceAll(".", " "), row.resourceType, formatDateTime(row.createdAt)])} emptyTitle="No recorded activity" />;
  };
  return <div className="space-y-6"><div><Button asChild size="sm" variant="ghost"><Link href="/admin/members"><ArrowLeft className="size-4" />Members</Link></Button><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">{data.overview.name}</h1><div className="mt-2 flex flex-wrap gap-2"><Badge>{data.overview.memberNumber}</Badge><StatusBadge status={data.overview.status} /><Badge variant="outline">Account: {data.overview.accountStatus}</Badge></div></div>{data.canManage ? <div className="flex flex-wrap gap-2"><Button disabled={data.overview.accountStatus === "ACTIVE"} onClick={() => setStatusTarget("ACTIVE")}>Activate</Button><Button disabled={data.overview.accountStatus === "SUSPENDED"} variant="outline" onClick={() => setStatusTarget("SUSPENDED")}>Suspend</Button><Button disabled={data.overview.accountStatus === "DISABLED"} variant="destructive" onClick={() => setStatusTarget("DISABLED")}><ShieldAlert className="size-4" />Disable</Button></div> : null}</div>{message ? <p className="mt-3 text-sm text-primary" role="status">{message}</p> : null}</div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border bg-card p-1" role="tablist" aria-label="Member sections">{tabs.filter((item) => !["Sponsor & Network", "Genealogy"].includes(item) || data.access.network).filter((item) => !["Commissions", "Wallet", "Withdrawals"].includes(item) || data.access.financials).filter((item) => item !== "Orders" || data.access.orders).filter((item) => item !== "Activity" || data.access.audit).map((item) => <Button key={item} role="tab" aria-selected={tab === item} size="sm" variant={tab === item ? "default" : "ghost"} className="shrink-0" onClick={() => setTab(item)}>{item}</Button>)}</div>
    <Card><CardHeader><CardTitle>{tab}</CardTitle><CardDescription>Member-scoped information. Financial history is read-only in this workspace.</CardDescription></CardHeader><CardContent>{section()}</CardContent></Card>
    {profileOpen ? <ProfileDialog open data={data.profile} saving={saving} onOpenChange={setProfileOpen} onSave={async (input) => { if (await mutate("profile", input)) setProfileOpen(false); }} /> : null}
    <ConfirmDialog open={Boolean(statusTarget)} onOpenChange={(open) => { if (!open) { setStatusTarget(null); setReason(""); } }} title={`${statusLabel}?`} description={statusTarget === "ACTIVE" ? "This restores normal protected application access for the member." : "This changes protected application access. The reason is kept in the audit log."} confirmLabel={statusLabel} destructive={statusTarget !== "ACTIVE"} confirming={saving} onConfirm={async () => { if (!statusTarget) return; if (await mutate("status", { status: statusTarget, ...(reason ? { reason } : {}) })) { setStatusTarget(null); setReason(""); } }}><>{statusTarget !== "ACTIVE" ? <label className="grid gap-2 text-sm font-medium">Reason <Textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} maxLength={500} placeholder="Explain why access is being restricted" /></label> : null}</></ConfirmDialog>
  </div>;
}

function ProfileDialog({ open, onOpenChange, data, onSave, saving }: { open: boolean; onOpenChange: (open: boolean) => void; data: Profile; onSave: (value: Profile) => Promise<void>; saving: boolean }) { const [form, setForm] = useState(data); const set = (key: keyof Profile, value: string) => setForm((current) => ({ ...current, [key]: value })); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Edit member profile</DialogTitle><DialogDescription>Only contact details can be updated here. Financial and identity access data remain protected.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value={form.firstName} onChange={(value) => set("firstName", value)} /><Field label="Last name" value={form.lastName} onChange={(value) => set("lastName", value)} /><Field label="Phone" value={form.phone} onChange={(value) => set("phone", value)} /><Field label="Alternate phone" value={form.alternatePhone} onChange={(value) => set("alternatePhone", value)} /></div><DialogFooter><Button variant="outline" disabled={saving} onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={saving || !form.firstName.trim() || !form.lastName.trim()} onClick={() => void onSave(form)}>{saving ? "Saving…" : "Save profile"}</Button></DialogFooter></DialogContent></Dialog>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-2 text-sm font-medium">{label}<Input value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-muted/20 p-4"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 break-words text-sm font-semibold">{value}</p></div>; }
function Rows({ rows, emptyTitle }: { rows: string[][]; emptyTitle: string }) { return rows.length ? <div className="space-y-2">{rows.map((row, index) => <div key={`${row.join("-")}-${index}`} className="grid gap-1 rounded-xl border p-3 text-sm sm:grid-cols-4 sm:gap-3">{row.map((value, itemIndex) => <span key={itemIndex} className={itemIndex === 0 ? "font-medium" : "text-muted-foreground"}>{value}</span>)}</div>)}</div> : <EmptyState title={emptyTitle} description="There are no records in this section yet." />; }
