import { Types } from "mongoose";

import { PERMISSION } from "@/config/permissions";
import { apiSuccess, withApiErrorHandling } from "@/lib/api";
import { requirePermission } from "@/lib/auth/authorization";
import { errors } from "@/lib/errors/app-error";
import { AuditLog, CommissionTransaction, MemberProfile, Order, SponsorRelationship, Wallet, Withdrawal } from "@/models";

export const GET = withApiErrorHandling(async (request: Request, { params }: { params: Promise<{ id: string }> }) => {
  await requirePermission(PERMISSION.MEMBERS.VIEW, request); const id = (await params).id; if (!Types.ObjectId.isValid(id)) throw errors.badRequest("Invalid member identifier.");
  const member = await MemberProfile.findById(id).populate("userId", "email status displayName").lean(); if (!member) throw errors.notFound("Member was not found."); const memberId = new Types.ObjectId(id);
  const [sponsorRelation, directRelations, wallet, withdrawals, orders, earnings, audit] = await Promise.all([SponsorRelationship.findOne({ memberProfileId: memberId }).lean(), SponsorRelationship.find({ sponsorMemberProfileId: memberId }).sort({ createdAt: -1 }).limit(12).lean(), Wallet.findOne({ memberProfileId: memberId }).lean(), Withdrawal.find({ memberProfileId: memberId }).sort({ createdAt: -1 }).limit(10).lean(), Order.find({ memberProfileId: memberId }).sort({ createdAt: -1 }).limit(10).lean(), CommissionTransaction.find({ recipientMemberProfileId: memberId }).sort({ createdAt: -1 }).limit(10).lean(), AuditLog.find({ resourceId: id }).sort({ createdAt: -1 }).limit(10).lean()]);
  const relatedIds = [...directRelations.map((row) => row.memberProfileId), ...(sponsorRelation ? [sponsorRelation.sponsorMemberProfileId] : [])]; const related = relatedIds.length ? await MemberProfile.find({ _id: { $in: relatedIds } }).select("memberNumber firstName lastName activationStatus joinedAt").lean() : []; const byId = new Map(related.map((row) => [String(row._id), row])); const sponsor = sponsorRelation ? byId.get(String(sponsorRelation.sponsorMemberProfileId)) : null;
  return apiSuccess({ overview: { id, memberNumber: member.memberNumber, name: `${member.firstName} ${member.lastName}`, email: (member.userId as unknown as { email?: string })?.email ?? "—", status: member.activationStatus, accountStatus: (member.userId as unknown as { status?: string })?.status ?? "—", joinedAt: member.joinedAt.toISOString() }, profile: { phone: member.phone ?? "—", alternatePhone: member.alternatePhone ?? "—", address: member.address ?? null }, sponsor: sponsor ? { memberNumber: sponsor.memberNumber, name: `${sponsor.firstName} ${sponsor.lastName}`, status: sponsor.activationStatus } : null, directReferrals: directRelations.flatMap((row) => { const profile = byId.get(String(row.memberProfileId)); return profile ? [{ memberNumber: profile.memberNumber, name: `${profile.firstName} ${profile.lastName}`, status: profile.activationStatus, joinedAt: profile.joinedAt.toISOString() }] : []; }), genealogy: { uplineMemberIds: sponsorRelation?.uplineMemberProfileIds.map(String) ?? [], directCount: directRelations.length }, wallet: wallet ? { currency: wallet.currency, availableMinor: wallet.availableMinor.toString(), heldMinor: wallet.heldMinor.toString(), lifetimeEarningsMinor: wallet.lifetimeEarningsMinor.toString() } : null, withdrawals: withdrawals.map((row) => ({ id: String(row._id), amountMinor: row.amountMinor.toString(), currency: row.currency, status: row.status, createdAt: row.createdAt.toISOString() })), orders: orders.map((row) => ({ id: String(row._id), orderNumber: row.orderNumber, totalMinor: row.totalMinor.toString(), currency: row.currency, status: row.status, createdAt: row.createdAt.toISOString() })), earnings: earnings.map((row) => ({ id: String(row._id), type: row.commissionType, amountMinor: row.amountMinor.toString(), currency: row.currency, status: row.status, createdAt: row.createdAt.toISOString() })), activity: audit.map((row) => ({ id: String(row._id), action: row.action, resourceType: row.resourceType, createdAt: row.createdAt.toISOString() })) });
});
