import "server-only";

import { type ClientSession, startSession, Types } from "mongoose";

import { MAX_INTERACTIVE_PAGE } from "@/config/pagination";
import { connectToDatabase } from "@/lib/db/mongoose";
import { errors } from "@/lib/errors/app-error";
import type { CommissionRuleInput } from "@/lib/validation/commission";
import { CommissionRule, CommissionTransaction, MemberProfile } from "@/models";
import { AuditService, type AuditRequestContext } from "@/services/audit/audit-service";

const transactionStatuses = ["PENDING", "APPROVED", "REVERSED", "VOID"] as const;
const transactionTypes = ["DIRECT", "LEVEL"] as const;
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const duplicateKey = (error: unknown) => typeof error === "object" && error !== null && "code" in error && (error as { code?: unknown }).code === 11000;

type TransactionFilters = { page: number; limit: number; member?: string; type?: (typeof transactionTypes)[number]; level?: number; status?: (typeof transactionStatuses)[number]; from?: Date; to?: Date; reference?: string };

function dateParam(value: string | null, end = false) { if (!value) return undefined; if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw errors.badRequest("Dates must use YYYY-MM-DD format."); const parsed = new Date(`${value}${end ? "T23:59:59.999Z" : "T00:00:00.000Z"}`); if (Number.isNaN(parsed.getTime())) throw errors.badRequest("Invalid date filter."); return parsed; }
function compact(value: string | null) { return value?.trim().slice(0, 100) || undefined; }
export function parseCommissionTransactionFilters(params: URLSearchParams): TransactionFilters {
  const page = Number(params.get("page") ?? 1); const limit = Number(params.get("limit") ?? 20); if (!Number.isSafeInteger(page) || !Number.isSafeInteger(limit) || page < 1 || page > MAX_INTERACTIVE_PAGE || limit < 1 || limit > 100) throw errors.badRequest("Invalid pagination.");
  const type = compact(params.get("type")); const status = compact(params.get("status")); const levelRaw = params.get("level"); const level = levelRaw ? Number(levelRaw) : undefined;
  if (type && !transactionTypes.includes(type as (typeof transactionTypes)[number])) throw errors.badRequest("Invalid commission type.");
  if (status && !transactionStatuses.includes(status as (typeof transactionStatuses)[number])) throw errors.badRequest("Invalid commission status.");
  if (level !== undefined && (!Number.isSafeInteger(level) || level < 1 || level > 100)) throw errors.badRequest("Invalid commission level.");
  const from = dateParam(params.get("from")); const to = dateParam(params.get("to"), true); if (from && to && from > to) throw errors.badRequest("The date range is invalid.");
  return { page, limit, ...(compact(params.get("member")) ? { member: compact(params.get("member")) } : {}), ...(type ? { type: type as TransactionFilters["type"] } : {}), ...(status ? { status: status as TransactionFilters["status"] } : {}), ...(level ? { level } : {}), ...(from ? { from } : {}), ...(to ? { to } : {}), ...(compact(params.get("reference")) ? { reference: compact(params.get("reference")) } : {}) };
}

function ruleData(input: CommissionRuleInput) { return { name: input.name, commissionType: input.commissionType, ...(input.commissionType === "LEVEL" ? { level: input.level } : { level: undefined }), calculationBasis: input.calculationBasis, rewardType: input.rewardType, ...(input.rewardType === "PERCENTAGE" ? { rateBasisPoints: input.percentage, fixedAmountMinor: undefined } : { fixedAmountMinor: BigInt(input.fixedAmountMinor!), rateBasisPoints: undefined }), active: input.active, effectiveFrom: new Date(`${input.effectiveFrom}T00:00:00.000Z`), ...(input.effectiveTo ? { effectiveTo: new Date(`${input.effectiveTo}T00:00:00.000Z`) } : { effectiveTo: undefined }) }; }
function ruleView(rule: { _id: Types.ObjectId; name: string; commissionType: string; level?: number; calculationBasis: string; rewardType: string; rateBasisPoints?: number; fixedAmountMinor?: bigint; active: boolean; effectiveFrom: Date; effectiveTo?: Date; createdAt: Date; updatedAt: Date }) { return { id: String(rule._id), name: rule.name, commissionType: rule.commissionType, level: rule.level ?? null, calculationBasis: rule.calculationBasis, rewardType: rule.rewardType, percentage: rule.rateBasisPoints != null ? (rule.rateBasisPoints / 100).toFixed(2) : null, fixedAmountMinor: rule.fixedAmountMinor?.toString() ?? null, active: rule.active, effectiveFrom: rule.effectiveFrom.toISOString(), effectiveTo: rule.effectiveTo?.toISOString() ?? null, createdAt: rule.createdAt.toISOString(), updatedAt: rule.updatedAt.toISOString() }; }

async function assertNoActiveOverlap(data: ReturnType<typeof ruleData>, excludeId?: string, session?: ClientSession) {
  const query = CommissionRule.findOne({ ...(excludeId ? { _id: { $ne: excludeId } } : {}), commissionType: data.commissionType, ...(data.commissionType === "LEVEL" ? { level: data.level } : { $or: [{ level: { $exists: false } }, { level: null }] }), active: true, effectiveFrom: { $lt: data.effectiveTo ?? new Date("9999-12-31T00:00:00.000Z") }, $and: [{ $or: [{ effectiveTo: null }, { effectiveTo: { $gt: data.effectiveFrom } }] }] });
  if (session) query.session(session);
  if (await query.lean()) throw errors.conflict("An active rule already covers this type, level, and effective period.");
}

export class CommissionManagementService {
  static async overview() { await connectToDatabase(); const [ruleCount, activeRuleCount, transactionCount, totals] = await Promise.all([CommissionRule.countDocuments(), CommissionRule.countDocuments({ active: true }), CommissionTransaction.countDocuments(), CommissionTransaction.aggregate<{ _id: string; amountMinor: bigint; count: number }>([{ $group: { _id: "$status", amountMinor: { $sum: "$amountMinor" }, count: { $sum: 1 } } }])]); return { ruleCount, activeRuleCount, transactionCount, totals: totals.map((row) => ({ status: row._id, amountMinor: row.amountMinor.toString(), count: row.count })) }; }
  static async rules() { await connectToDatabase(); const rules = await CommissionRule.find().sort({ commissionType: 1, level: 1, effectiveFrom: -1 }).limit(100).lean(); return rules.map(ruleView); }
  static async createRule(input: CommissionRuleInput, actorUserId: Types.ObjectId, audit: AuditRequestContext) { const data = ruleData(input); await connectToDatabase(); const session = await startSession(); try { let created: { _id: Types.ObjectId } | undefined; await session.withTransaction(async () => { if (data.active) await assertNoActiveOverlap(data, undefined, session); const [rule] = await CommissionRule.create([data], { session }); created = rule; await AuditService.record({ actorUserId, ...audit, action: "commission.rule_created", resourceType: "CommissionRule", resourceId: String(rule._id), after: ruleView(rule) }, session); }); if (!created) throw errors.conflict("Commission rule was not created."); return { id: String(created._id) }; } catch (error) { if (duplicateKey(error)) throw errors.conflict("A commission rule already starts at that type, level, and effective date."); throw error; } finally { await session.endSession(); } }
  static async updateRule(id: string, input: CommissionRuleInput, actorUserId: Types.ObjectId, audit: AuditRequestContext) { if (!Types.ObjectId.isValid(id)) throw errors.badRequest("Invalid commission rule identifier."); const data = ruleData(input); await connectToDatabase(); const session = await startSession(); try { await session.withTransaction(async () => { const rule = await CommissionRule.findById(id).session(session); if (!rule) throw errors.notFound("Commission rule was not found."); const used = await CommissionTransaction.exists({ commissionRuleId: rule._id }).session(session); const calculationChanged = rule.commissionType !== data.commissionType || rule.level !== data.level || rule.calculationBasis !== data.calculationBasis || rule.rewardType !== data.rewardType || rule.rateBasisPoints !== data.rateBasisPoints || rule.fixedAmountMinor !== data.fixedAmountMinor || rule.effectiveFrom.getTime() !== data.effectiveFrom.getTime(); if (used && calculationChanged) throw errors.conflict("A rule with historical commissions cannot be recalculated or changed. Create a new future-effective rule instead."); if (data.active) await assertNoActiveOverlap(data, id, session); const before = ruleView(rule); Object.assign(rule, data); await rule.save({ session }); const after = ruleView(rule); await AuditService.record({ actorUserId, ...audit, action: before.active !== after.active ? after.active ? "commission.rule_activated" : "commission.rule_deactivated" : "commission.rule_updated", resourceType: "CommissionRule", resourceId: id, before, after }, session); }); } catch (error) { if (duplicateKey(error)) throw errors.conflict("A commission rule already starts at that type, level, and effective date."); throw error; } finally { await session.endSession(); } }
  static async transactions(filters: TransactionFilters) { await connectToDatabase(); const clauses: Record<string, unknown>[] = []; if (filters.type) clauses.push({ commissionType: filters.type }); if (filters.status) clauses.push({ status: filters.status }); if (filters.level) clauses.push({ level: filters.level }); if (filters.from || filters.to) clauses.push({ createdAt: { ...(filters.from ? { $gte: filters.from } : {}), ...(filters.to ? { $lte: filters.to } : {}) } }); if (filters.reference) { const regex = new RegExp(escapeRegex(filters.reference), "i"); clauses.push({ $or: [{ sourceReferenceId: regex }, { sourceOrderId: regex }] }); } if (filters.member) { const regex = new RegExp(escapeRegex(filters.member), "i"); const profiles = await MemberProfile.find({ $or: [{ memberNumber: regex }, { referralCode: regex }, { firstName: regex }, { lastName: regex }] }).select("_id").limit(1_000).lean(); const ids = profiles.map((profile) => profile._id); if (!ids.length) return { items: [], pagination: { total: 0, page: filters.page, limit: filters.limit, totalPages: 1 } }; clauses.push({ $or: [{ recipientMemberProfileId: { $in: ids } }, { sourceMemberProfileId: { $in: ids } }] }); }
    const query = clauses.length ? { $and: clauses } : {}; const [rows, total] = await Promise.all([CommissionTransaction.find(query).sort({ createdAt: -1, _id: -1 }).skip((filters.page - 1) * filters.limit).limit(filters.limit).lean(), CommissionTransaction.countDocuments(query)]); const ids = [...new Set(rows.flatMap((row) => [String(row.recipientMemberProfileId), String(row.sourceMemberProfileId)]))]; const profiles = ids.length ? await MemberProfile.find({ _id: { $in: ids } }).select("memberNumber firstName lastName").lean() : []; const byId = new Map(profiles.map((profile) => [String(profile._id), profile])); return { items: rows.map((row) => { const beneficiary = byId.get(String(row.recipientMemberProfileId)); const source = byId.get(String(row.sourceMemberProfileId)); return { id: String(row._id), beneficiary: beneficiary ? { id: String(row.recipientMemberProfileId), memberNumber: beneficiary.memberNumber, name: `${beneficiary.firstName} ${beneficiary.lastName}` } : null, sourceMember: source ? { id: String(row.sourceMemberProfileId), memberNumber: source.memberNumber, name: `${source.firstName} ${source.lastName}` } : null, sourceOrder: row.sourceReferenceId, sourceOrderId: row.sourceOrderId ? String(row.sourceOrderId) : null, walletTransactionId: row.walletTransactionId ? String(row.walletTransactionId) : null, type: row.commissionType, level: row.level ?? null, calculationBasis: row.calculationBasis, rate: row.rewardType === "PERCENTAGE" ? `${((row.rateBasisPoints ?? 0) / 100).toFixed(2)}%` : `${row.fixedAmountMinor?.toString() ?? "0"} minor units`, amountMinor: row.amountMinor.toString(), baseAmountMinor: row.baseAmountMinor.toString(), currency: row.currency, status: row.status, date: row.createdAt.toISOString(), ruleId: String(row.commissionRuleId) }; }), pagination: { total, page: filters.page, limit: filters.limit, totalPages: Math.max(1, Math.ceil(total / filters.limit)) } }; }
}
