import type { Metadata } from "next";
import { Check, Network, ShieldCheck, WalletCards } from "lucide-react";

export const metadata: Metadata = { title: "About", description: "Learn how Nexora governs member networks, financial records, and administrative access.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  const principles = [["Relationships before reports", "Genealogy and sponsorship are durable server-side relationships, so the numbers have a source.", Network], ["Financial actions leave evidence", "Commissions, wallet entries, and withdrawals use referenced, immutable records rather than editable totals.", WalletCards], ["Authority is verified", "Firebase confirms identity. Nexora resolves account status, roles, and permissions before it authorizes a protected action.", ShieldCheck]] as const;
  return <section><div className="grid gap-8 border-b border-black/15 pb-12 lg:grid-cols-[.8fr_1.2fr]"><p className="eyebrow text-primary">About Nexora</p><div><h1 className="display-type max-w-4xl text-5xl font-bold sm:text-7xl">Network management made accountable.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Nexora is an operational home for members and administrators. It is designed around one question: can every important action be understood, authorized, and traced?</p></div></div><div className="grid divide-y divide-black/10 md:grid-cols-3 md:divide-x md:divide-y-0">{principles.map(([title, copy, Icon], index) => <article key={title} className="py-10 md:px-7 md:first:pl-0 md:last:pr-0"><div className="flex items-center justify-between"><span className="font-mono text-sm text-muted-foreground">0{index + 1}</span><Icon className="size-5" /></div><h2 className="mt-16 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p><p className="mt-6 flex items-center gap-2 text-sm font-semibold"><Check className="size-4 text-primary" />Built into the platform</p></article>)}</div></section>;
}
