import { PERMISSION } from "@/config/permissions";
import { apiSuccess, withApiErrorHandling } from "@/lib/api";
import { requirePermission, requireRole } from "@/lib/auth/authorization";
import { errors } from "@/lib/errors/app-error";
import { AuditLog, CommissionTransaction, MemberProfile, Notification, Payment, Permission, Role, Setting, User, WalletTransaction } from "@/models";
import { MAX_INTERACTIVE_PAGE } from "@/config/pagination";

const resources = ["members", "commissions", "wallet-transactions", "payments", "staff", "roles", "permissions", "settings", "notifications", "audit-logs"] as const;
type Resource = (typeof resources)[number];
const permissionFor: Record<Resource, Parameters<typeof requirePermission>[0]> = { members: PERMISSION.MEMBERS.VIEW, commissions: PERMISSION.COMMISSIONS.VIEW_ALL, "wallet-transactions": PERMISSION.WALLET.VIEW_ALL, payments: PERMISSION.PAYMENTS.VIEW, staff: PERMISSION.STAFF.VIEW, roles: PERMISSION.ROLES.VIEW, permissions: PERMISSION.ROLES.VIEW, settings: PERMISSION.SETTINGS.VIEW, notifications: PERMISSION.NOTIFICATIONS.VIEW, "audit-logs": PERMISSION.AUDIT.VIEW };
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function filters(url: URL) { const page = Number(url.searchParams.get("page") ?? 1); const limit = Number(url.searchParams.get("limit") ?? 20); const sort: 1 | -1 = url.searchParams.get("sort") === "oldest" ? 1 : -1; const status = url.searchParams.get("status")?.trim(); const search = url.searchParams.get("q")?.trim().slice(0, 100); if (!Number.isSafeInteger(page) || !Number.isSafeInteger(limit) || page < 1 || page > MAX_INTERACTIVE_PAGE || limit < 1 || limit > 100) throw errors.badRequest("Invalid pagination."); return { page, limit, sort, ...(status ? { status } : {}), ...(search ? { search } : {}) }; }
function page<T>(items: T[], total: number, input: ReturnType<typeof filters>) { return { items, pagination: { total, page: input.page, limit: input.limit, totalPages: Math.max(1, Math.ceil(total / input.limit)) } }; }
function stamp(value: Date | undefined) { return value?.toISOString() ?? null; }

export const GET = withApiErrorHandling(async (request: Request, { params }: { params: Promise<{ resource: string }> }) => {
  const resource = (await params).resource as Resource; if (!resources.includes(resource)) throw errors.notFound(); const context = resource === "settings" ? await requireRole("SUPER_ADMIN", request) : await requirePermission(permissionFor[resource], request); const input = filters(new URL(request.url)); const skip = (input.page - 1) * input.limit;
  if (resource === "members") {
    const query: Record<string, unknown> = { ...(input.status ? { activationStatus: input.status } : {}), ...(input.search ? { $or: [{ memberNumber: new RegExp(escapeRegex(input.search), "i") }, { firstName: new RegExp(escapeRegex(input.search), "i") }, { lastName: new RegExp(escapeRegex(input.search), "i") }] } : {}) };
    const [rows, total] = await Promise.all([MemberProfile.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).populate("userId", "email status").lean(), MemberProfile.countDocuments(query)]);
    return apiSuccess(page(rows.map((row) => { const user = row.userId as unknown as { email?: string; status?: string }; return { id: String(row._id), memberNumber: row.memberNumber, name: `${row.firstName} ${row.lastName}`, email: user?.email ?? "—", status: row.activationStatus, accountStatus: user?.status ?? "—", joinedAt: stamp(row.joinedAt) }; }), total, input));
  }
  if (resource === "commissions") {
    const query = { ...(input.status ? { status: input.status } : {}) }; const [rows, total] = await Promise.all([CommissionTransaction.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).lean(), CommissionTransaction.countDocuments(query)]); const profiles = rows.length ? await MemberProfile.find({ _id: { $in: rows.map((row) => row.recipientMemberProfileId) } }).select("memberNumber firstName lastName").lean() : []; const lookup = new Map(profiles.map((profile) => [String(profile._id), profile])); return apiSuccess(page(rows.map((row) => { const profile = lookup.get(String(row.recipientMemberProfileId)); return { id: String(row._id), member: profile ? `${profile.firstName} ${profile.lastName}` : "Unknown member", memberNumber: profile?.memberNumber ?? "—", type: row.commissionType, level: row.level ?? null, amountMinor: row.amountMinor.toString(), currency: row.currency, status: row.status, reference: row.sourceReferenceId, createdAt: stamp(row.createdAt) }; }), total, input));
  }
  if (resource === "wallet-transactions") {
    const query = { ...(input.status ? { type: input.status } : {}) }; const [rows, total] = await Promise.all([WalletTransaction.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).lean(), WalletTransaction.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), memberId: String(row.memberProfileId), type: row.type, direction: row.direction, amountMinor: row.amountMinor.toString(), currency: row.currency, description: row.description, reference: `${row.referenceType}:${row.referenceId}`, createdAt: stamp(row.createdAt) })), total, input));
  }
  if (resource === "payments") {
    const query = { ...(input.status ? { status: input.status } : {}) }; const [rows, total] = await Promise.all([Payment.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).lean(), Payment.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), orderId: String(row.orderId), provider: row.provider, providerTransactionId: row.providerTransactionId ?? "—", amountMinor: row.amountMinor.toString(), currency: row.currency, status: row.status, createdAt: stamp(row.createdAt) })), total, input));
  }
  if (resource === "staff") {
    const staffRoleIds = (await Role.find({ baseRole: { $in: ["SUPER_ADMIN", "ADMIN", "STAFF"] }, isActive: true }).select("_id").lean()).map((role) => role._id);
    const query = {
      roleIds: { $in: staffRoleIds },
      ...(input.search ? { $or: [{ displayName: new RegExp(escapeRegex(input.search), "i") }, { email: new RegExp(escapeRegex(input.search), "i") }] } : {}),
    };
    const [rows, total] = await Promise.all([User.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).populate("roleIds", "name").lean(), User.countDocuments(query)]);
    return apiSuccess(page(rows.map((row) => ({ id: String(row._id), name: row.displayName, email: row.email, status: row.status, roles: (row.roleIds as unknown as Array<{ name: string }>).map((role) => role.name), createdAt: stamp(row.createdAt) })), total, input));
  }
  if (resource === "roles") { const query = { ...(input.status === "ACTIVE" ? { isActive: true } : input.status === "INACTIVE" ? { isActive: false } : {}), ...(input.search ? { $or: [{ name: new RegExp(escapeRegex(input.search), "i") }, { slug: new RegExp(escapeRegex(input.search), "i") }, { baseRole: new RegExp(escapeRegex(input.search), "i") }] } : {}) }; const [rows, total] = await Promise.all([Role.find(query).sort({ name: 1 }).skip(skip).limit(input.limit).lean(), Role.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), name: row.name, slug: row.slug, description: row.description ?? "", baseRole: row.baseRole, isSystem: row.isSystem, isActive: row.isActive, permissions: row.permissions, createdAt: stamp(row.createdAt) })), total, input)); }
  if (resource === "permissions") { const query = input.search ? { $or: [{ key: new RegExp(escapeRegex(input.search), "i") }, { name: new RegExp(escapeRegex(input.search), "i") }, { module: new RegExp(escapeRegex(input.search), "i") }] } : {}; const [rows, total] = await Promise.all([Permission.find(query).sort({ module: 1, key: 1 }).skip(skip).limit(input.limit).lean(), Permission.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), key: row.key, name: row.name, module: row.module, description: row.description ?? "" })), total, input)); }
  if (resource === "settings") { const [rows, total] = await Promise.all([Setting.find().select("+isSecret").sort({ key: 1 }).skip(skip).limit(input.limit).lean(), Setting.countDocuments()]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), key: row.key, value: row.isSecret ? "••••••" : row.value, valueType: row.valueType, isSecret: row.isSecret, updatedAt: stamp(row.updatedAt) })), total, input)); }
  if (resource === "notifications") { const query = { userId: context.user._id, ...(input.status === "UNREAD" ? { readAt: null } : input.status === "READ" ? { readAt: { $ne: null } } : {}) }; const [rows, total] = await Promise.all([Notification.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).lean(), Notification.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), userId: String(row.userId), type: row.type, title: row.title, body: row.body, read: Boolean(row.readAt), createdAt: stamp(row.createdAt) })), total, input)); }
  const query = input.search ? { $or: [{ action: new RegExp(escapeRegex(input.search), "i") }, { resourceType: new RegExp(escapeRegex(input.search), "i") }] } : {}; const [rows, total] = await Promise.all([AuditLog.find(query).sort({ createdAt: input.sort, _id: input.sort }).skip(skip).limit(input.limit).lean(), AuditLog.countDocuments(query)]); return apiSuccess(page(rows.map((row) => ({ id: String(row._id), action: row.action, resourceType: row.resourceType, resourceId: row.resourceId ?? "—", actorUserId: row.actorUserId ? String(row.actorUserId) : "System", createdAt: stamp(row.createdAt) })), total, input));
});
