"use client";

import { motion, useReducedMotion } from "framer-motion";
import { BadgeIndianRupee, CheckCircle2, CircleDollarSign, CreditCard, ReceiptText, ShieldCheck, ShoppingBag, TrendingUp, Users, WalletCards, type LucideIcon } from "lucide-react";
import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useCallback, useEffect, useMemo, useState } from "react";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { DateRangeFilter } from "@/components/admin/date-range-filter";
import { LoadingSkeleton } from "@/components/admin/loading-skeleton";
import { StatusBadge } from "@/components/admin/status-badge";
import { ErrorState } from "@/components/shared/states";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency, formatDateTime } from "@/lib/utils/format";

type RangeKey = "today" | "7d" | "30d" | "month" | "custom";
type Dashboard = ReturnType<typeof import("@/services/dashboard/dashboard-access").scopeDashboard>;
type Envelope<T> = { success: true; data: T } | { success: false; error?: { message?: string } };
type MetricProps = { icon: LucideIcon; label: string; value: string; detail: string; href?: string; prominent?: boolean; tone?: string };

const rangeOptions: Array<{ key: Exclude<RangeKey, "custom">; label: string }> = [{ key: "today", label: "Today" }, { key: "7d", label: "7 Days" }, { key: "30d", label: "30 Days" }, { key: "month", label: "This Month" }];
const motionItem = { hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } };
const isoDate = (date: Date) => date.toISOString().slice(0, 10);
const graphAmount = (minor: string) => Number(BigInt(minor) / 100n);

async function requestDashboard(query: string) {
  const response = await fetch(`/api/v1/admin/dashboard?${query}`, { cache: "no-store" });
  const body = await response.json() as Envelope<Dashboard>;
  if (!response.ok || !body.success) throw new Error(!body.success ? body.error?.message ?? "Dashboard could not be loaded." : "Dashboard could not be loaded.");
  return body.data;
}

function MetricCard({ icon: Icon, label, value, detail, href, prominent = false, tone = "bg-primary/10 text-primary" }: MetricProps) {
  const content = <Card className={prominent ? "border-amber-400/70 bg-amber-50/60 shadow-sm dark:bg-amber-950/10" : "transition-shadow hover:shadow-md"}><CardContent className="flex items-start justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 truncate text-xl font-bold tracking-tight">{value}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{detail}</p></div><span className={`grid size-9 shrink-0 place-items-center rounded-lg ${tone}`}><Icon className="size-4" aria-hidden="true" /></span></CardContent></Card>;
  return href ? <Link className="rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" href={href} aria-label={`${label}: ${value}. ${detail}`}>{content}</Link> : content;
}

function SectionHeader({ title, description, href, action }: { title: string; description?: string; href?: string; action?: string }) {
  return <CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle>{title}</CardTitle>{description ? <CardDescription className="mt-1">{description}</CardDescription> : null}</div>{href && action ? <Button size="sm" variant="ghost" asChild><Link href={href}>{action}</Link></Button> : null}</CardHeader>;
}

function EmptyFeed({ children }: { children: string }) { return <p className="px-6 pb-6 text-sm leading-6 text-muted-foreground">{children}</p>; }

function Chart({ title, description, type, data, currency }: { title: string; description: string; type: "members" | "sales" | "commission" | "withdrawal"; data: Array<{ label: string; amount?: number; count?: number }>; currency: string }) {
  const isMembers = type === "members";
  const color = type === "sales" ? "hsl(152 69% 31%)" : type === "commission" ? "hsl(262 83% 58%)" : type === "withdrawal" ? "hsl(25 95% 53%)" : "hsl(var(--primary))";
  return <Card><SectionHeader title={title} description={description} /><CardContent className="h-64"><ResponsiveContainer width="100%" height="100%">{isMembers ? <AreaChart data={data} margin={{ left: -15, right: 8, top: 6 }}><defs><linearGradient id="admin-member-growth" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={0.32} /><stop offset="100%" stopColor={color} stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={24} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><Tooltip contentStyle={{ borderRadius: 12, borderColor: "hsl(var(--border))" }} /><Area type="monotone" dataKey="count" name="Members" stroke={color} strokeWidth={2.5} fill="url(#admin-member-growth)" /></AreaChart> : type === "sales" ? <AreaChart data={data} margin={{ left: -15, right: 8, top: 6 }}><defs><linearGradient id="admin-sales-trend" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={0.3} /><stop offset="100%" stopColor={color} stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={24} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><Tooltip formatter={(value) => [formatCurrency(BigInt(Math.round(Number(value) * 100)), currency), "Sales"]} contentStyle={{ borderRadius: 12, borderColor: "hsl(var(--border))" }} /><Area type="monotone" dataKey="amount" name="Sales" stroke={color} strokeWidth={2.5} fill="url(#admin-sales-trend)" /></AreaChart> : <BarChart data={data} margin={{ left: -15, right: 8, top: 6 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={24} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><Tooltip formatter={(value) => [formatCurrency(BigInt(Math.round(Number(value) * 100)), currency), title]} contentStyle={{ borderRadius: 12, borderColor: "hsl(var(--border))" }} /><Bar dataKey="amount" name={title} radius={[7, 7, 0, 0]} fill={color} /></BarChart>}</ResponsiveContainer></CardContent></Card>;
}

export function AdminDashboard() {
  const [initialDates] = useState(() => { const end = new Date(); return { from: isoDate(new Date(end.getTime() - 29 * 86_400_000)), to: isoDate(end) }; });
  const reducedMotion = useReducedMotion();
  const [range, setRange] = useState<RangeKey>("30d");
  const [draftRange, setDraftRange] = useState(initialDates);
  const [appliedRange, setAppliedRange] = useState(initialDates);
  const [data, setData] = useState<Dashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const query = useMemo(() => { const params = new URLSearchParams({ range }); if (range === "custom") { params.set("from", appliedRange.from); params.set("to", appliedRange.to); } return params.toString(); }, [range, appliedRange]);
  const load = useCallback(async () => { setLoading(true); try { setData(await requestDashboard(query)); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Dashboard could not be loaded."); } finally { setLoading(false); } }, [query]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);

  if (!data && loading) return <LoadingSkeleton rows={4} columns={4} />;
  if (!data) return <ErrorState title="Dashboard could not be loaded" description={error ?? "Please try again."} action={<Button variant="outline" onClick={() => void load()}>Try again</Button>} />;

  const memberGrowth = data.charts.memberGrowth.map((item) => ({ label: item.label, count: item.count }));
  const sales = data.charts.salesTrend.map((item) => ({ label: item.label, amount: graphAmount(item.amountMinor) }));
  const commissions = data.charts.commissionTrend.map((item) => ({ label: item.label, amount: graphAmount(item.amountMinor) }));
  const withdrawals = data.charts.withdrawalTrend.map((item) => ({ label: item.label, amount: graphAmount(item.amountMinor) }));
  const newMembers = data.metrics.newMembers ?? 0;
  const previousNewMembers = data.metrics.previousNewMembers ?? 0;
  const priorMemberDetail = previousNewMembers ? `${newMembers >= previousNewMembers ? "+" : ""}${newMembers - previousNewMembers} vs previous period` : `${newMembers} in selected period`;

  return <motion.div initial={reducedMotion ? false : "hidden"} animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: reducedMotion ? 0 : 0.035 } } }} className="space-y-6 pb-5">
    <motion.section variants={motionItem}><AdminPageHeader eyebrow="Super Admin workspace" title="Operations dashboard" description={`Live MongoDB-backed platform activity for ${data.range.label}.`} actions={<div className="flex flex-wrap gap-2 rounded-xl border bg-card p-1.5">{rangeOptions.map((option) => <Button key={option.key} size="sm" variant={range === option.key ? "default" : "ghost"} onClick={() => setRange(option.key)}>{option.label}</Button>)}<Button size="sm" variant={range === "custom" ? "default" : "ghost"} onClick={() => setRange("custom")}>Custom range</Button></div>} />{range === "custom" ? <div className="rounded-xl border bg-muted/20 p-3"><DateRangeFilter value={draftRange} onChange={setDraftRange} onApply={() => setAppliedRange(draftRange)} disabled={loading} /></div> : null}</motion.section>
    {error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">The last refresh failed: {error}</p> : null}
    <motion.section variants={motionItem} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard icon={Users} label="Total members" value={String(data.metrics.totalMembers)} detail={`${data.metrics.activeMembers} active members`} href="/admin/members" /><MetricCard icon={TrendingUp} label="New members" value={String(newMembers)} detail={priorMemberDetail} href="/admin/members" tone="bg-violet-500/10 text-violet-700" />{data.access.sales ? <><MetricCard icon={ShoppingBag} label="Total sales" value={formatCurrency(data.metrics.totalSalesMinor!, data.currency)} detail={`${formatCurrency(data.metrics.salesInRangeMinor!, data.currency)} in selected period`} href="/admin/orders" tone="bg-emerald-500/10 text-emerald-700" /><MetricCard icon={ReceiptText} label="Total orders" value={String(data.metrics.totalOrders!)} detail={`${data.metrics.ordersInRange!} created in selected period`} href="/admin/orders" tone="bg-indigo-500/10 text-indigo-700" /><MetricCard icon={CheckCircle2} label="Successful payments" value={String(data.metrics.successfulPayments!)} detail={`${data.metrics.successfulPaymentsInRange!} settled in selected period`} href="/admin/payments" tone="bg-teal-500/10 text-teal-700" /></> : null}{data.access.finance ? <><MetricCard icon={CircleDollarSign} label="Total commission" value={formatCurrency(data.metrics.totalCommissionMinor!, data.currency)} detail={`${formatCurrency(data.metrics.commissionInRangeMinor!, data.currency)} approved in selected period`} href="/admin/commissions" tone="bg-sky-500/10 text-sky-700" /><MetricCard icon={WalletCards} label="Wallet liability" value={formatCurrency(data.metrics.walletLiabilityMinor!, data.currency)} detail="Available plus held balances" href="/admin/wallet" tone="bg-rose-500/10 text-rose-700" /><MetricCard icon={CreditCard} label="Pending withdrawals" value={formatCurrency(data.metrics.pendingWithdrawalsMinor!, data.currency)} detail={`${data.metrics.pendingWithdrawalCount!} require operational review`} href="/admin/withdrawals" prominent={data.metrics.pendingWithdrawalCount! > 0} tone="bg-amber-500/10 text-amber-700" /><MetricCard icon={BadgeIndianRupee} label="Completed withdrawals" value={formatCurrency(data.metrics.completedWithdrawalsMinor!, data.currency)} detail={`${data.metrics.completedWithdrawalCount!} completed · ${formatCurrency(data.metrics.completedWithdrawalsInRangeMinor!, data.currency)} in range`} href="/admin/withdrawals" tone="bg-emerald-500/10 text-emerald-700" /></> : null}</motion.section>
    <motion.section variants={motionItem} className="grid gap-6 xl:grid-cols-2"><Chart title="Member growth" description="New member profiles over the selected range" type="members" data={memberGrowth} currency={data.currency} />{data.access.sales ? <Chart title="Sales trend" description="Verified payments only" type="sales" data={sales} currency={data.currency} /> : null}{data.access.finance ? <Chart title="Commission trend" description="Approved commission credits" type="commission" data={commissions} currency={data.currency} /> : null}{data.access.finance ? <Chart title="Withdrawal trend" description="Completed withdrawals" type="withdrawal" data={withdrawals} currency={data.currency} /> : null}</motion.section>
    <motion.section variants={motionItem} className="grid gap-6 xl:grid-cols-3">{data.access.members ? <Card><SectionHeader title="Recent members" description="Latest registrations" href="/admin/members" action="View all" /><CardContent className="space-y-1">{data.recentMembers.length ? data.recentMembers.map((member) => <Link key={member.id} href={`/admin/members/${member.id}`} className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="min-w-0"><p className="truncate text-sm font-medium">{member.name}</p><p className="text-xs text-muted-foreground">{member.memberNumber} · {formatDateTime(member.joinedAt)}</p></div><StatusBadge status={member.status} /></Link>) : <EmptyFeed>No member profiles have been created yet.</EmptyFeed>}</CardContent></Card> : null}{data.access.withdrawals ? <Card className={data.pendingWithdrawals.length ? "border-amber-400/60" : undefined}><SectionHeader title="Pending withdrawals" description="Oldest requests first" href="/admin/withdrawals" action="Open queue" /><CardContent className="space-y-1">{data.pendingWithdrawals.length ? data.pendingWithdrawals.map((withdrawal) => <Link key={withdrawal.id} href="/admin/withdrawals" className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="min-w-0"><p className="truncate text-sm font-medium">{withdrawal.memberName}</p><p className="text-xs text-muted-foreground">{withdrawal.memberNumber} · {formatDateTime(withdrawal.createdAt)}</p></div><div className="text-right"><p className="text-sm font-bold">{formatCurrency(withdrawal.amountMinor, withdrawal.currency)}</p><StatusBadge status={withdrawal.status} /></div></Link>) : <EmptyFeed>No withdrawals require review right now.</EmptyFeed>}</CardContent></Card> : null}{data.access.orders ? <Card><SectionHeader title="Recent orders" description="Latest checkout activity" href="/admin/orders" action="View all" /><CardContent className="space-y-1">{data.recentOrders.length ? data.recentOrders.map((order) => <Link key={order.id} href="/admin/orders" className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="min-w-0"><p className="text-sm font-medium">{order.orderNumber}</p><p className="truncate text-xs text-muted-foreground">{order.memberName} · {order.paymentStatus}</p></div><div className="text-right"><p className="text-sm font-bold">{formatCurrency(order.totalMinor, order.currency)}</p><StatusBadge status={order.status} /></div></Link>) : <EmptyFeed>No orders have been placed yet.</EmptyFeed>}</CardContent></Card> : null}</motion.section>
    <motion.section variants={motionItem} className="grid gap-6 lg:grid-cols-3">{data.access.sales ? <Card><SectionHeader title="Recent payments" description="Provider-normalized payment activity" href="/admin/payments" action="View all" /><CardContent className="space-y-1">{data.recentPayments.length ? data.recentPayments.map((payment) => <Link key={payment.id} href="/admin/payments" className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="min-w-0"><p className="truncate text-sm font-medium">{payment.orderNumber}</p><p className="truncate text-xs text-muted-foreground">{payment.memberName} · {payment.provider} · {formatDateTime(payment.createdAt)}</p></div><div className="text-right"><p className="text-sm font-bold">{formatCurrency(payment.amountMinor, payment.currency)}</p><StatusBadge status={payment.status} /></div></Link>) : <EmptyFeed>No payment activity has been recorded yet.</EmptyFeed>}</CardContent></Card> : null}{data.access.commissions ? <Card><SectionHeader title="Recent commissions" description="Latest immutable commission records" href="/admin/commissions" action="View all" /><CardContent className="space-y-1">{data.recentCommissions.length ? data.recentCommissions.map((commission) => <Link key={commission.id} href="/admin/commissions" className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="min-w-0"><p className="truncate text-sm font-medium">{commission.type}</p><p className="truncate text-xs text-muted-foreground">{commission.memberName} · {commission.memberNumber}</p></div><div className="text-right"><p className="text-sm font-bold text-emerald-700">{formatCurrency(commission.amountMinor, commission.currency)}</p><StatusBadge status={commission.status} /></div></Link>) : <EmptyFeed>No commission records have been created yet.</EmptyFeed>}</CardContent></Card> : null}{data.access.audit ? <Card><SectionHeader title="Recent admin activity" description="Most recent immutable audit events" href="/admin/audit-logs" action="View all" /><CardContent className="space-y-1">{data.securityActivity.length ? data.securityActivity.map((activity) => <Link key={activity.id} href="/admin/audit-logs" className="flex items-start gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-slate-500/10 text-slate-700"><ShieldCheck className="size-4" /></div><div className="min-w-0"><p className="truncate text-sm font-medium">{activity.action.replaceAll(".", " ")}</p><p className="truncate text-xs text-muted-foreground">{activity.actorName} · {activity.resourceType} · {formatDateTime(activity.createdAt)}</p></div></Link>) : <EmptyFeed>Audit activity will appear here as authorized operations occur.</EmptyFeed>}</CardContent></Card> : null}</motion.section>
  </motion.div>;
}
