"use client";

import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { motion, useReducedMotion } from "framer-motion";
import { Bell, Copy, CreditCard, Gift, Network, ShoppingBag, TrendingUp, Users, WalletCards, type LucideIcon } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import { EmptyState, ErrorState } from "@/components/shared/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCurrency, formatDateTime } from "@/lib/utils/format";

type DashboardData = {
  member: { firstName: string; memberNumber: string; referralCode: string }; currency: string;
  metrics: { availableBalanceMinor: string; lifetimeEarningsMinor: string; directReferrals: number; totalTeam: number; pendingWithdrawalMinor: string; orders: number };
  charts: { earnings: Array<{ label: string; amountMinor: string }>; commissionBreakdown: Array<{ name: "Direct" | "Level"; amountMinor: string }>; teamGrowth: Array<{ label: string; members: number }> };
  recentEarnings: Array<{ id: string; type: "DIRECT" | "LEVEL"; level?: number; amountMinor: string; currency: string; sourceMemberName: string; createdAt: string }>;
  recentWalletTransactions: Array<{ id: string; type: string; direction: "CREDIT" | "DEBIT"; amountMinor: string; description: string; createdAt: string }>;
  recentReferrals: Array<{ memberNumber: string; name: string; status: string; joinedAt: string }>;
  recentOrders: Array<{ id: string; orderNumber: string; totalMinor: string; status: string; paymentStatus: string; createdAt: string }>;
  notifications: Array<{ id: string; type: string; title: string; body: string; actionUrl?: string; createdAt: string; read: boolean }>;
  referral: { url: string; directReferrals: number; teamMembers: number };
};
type Envelope<T> = { success: true; data: T } | { success: false; error?: { message?: string } };
const fade = { hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } };
const graphAmount = (minor: string) => Number(BigInt(minor) / 100n);

async function getDashboard() { const response = await fetch("/api/v1/dashboard/member", { cache: "no-store" }); const result = await response.json() as Envelope<DashboardData>; if (!response.ok || !result.success) throw new Error(!result.success ? result.error?.message ?? "Dashboard could not be loaded." : "Dashboard could not be loaded."); return result.data; }
function SkeletonDashboard() { return <div className="space-y-6"><Skeleton className="h-40" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, i) => <Skeleton key={i} className="h-32" />)}</div><div className="grid gap-6 xl:grid-cols-3"><Skeleton className="h-80 xl:col-span-2" /><Skeleton className="h-80" /></div></div>; }
function Metric({ icon: Icon, label, value, detail, color = "bg-primary/10 text-primary" }: { icon: LucideIcon; label: string; value: string; detail: string; color?: string }) { return <Card className="group overflow-hidden transition-shadow hover:shadow-md"><CardContent className="relative flex items-start justify-between gap-3 p-5"><div className="absolute -right-6 -top-6 size-24 rounded-full bg-primary/[0.04] transition-transform group-hover:scale-125" /><div className="relative"><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><div className={`relative grid size-11 shrink-0 place-items-center rounded-xl ${color}`}><Icon className="size-5" /></div></CardContent></Card>; }
function Header({ title, description, href, action }: { title: string; description?: string; href?: string; action?: string }) { return <CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle>{title}</CardTitle>{description ? <CardDescription className="mt-1">{description}</CardDescription> : null}</div>{href && action ? <Button size="sm" variant="ghost" asChild><Link href={href}>{action}</Link></Button> : null}</CardHeader>; }
function NoActivity({ children }: { children: string }) { return <p className="px-6 pb-6 text-sm leading-6 text-muted-foreground">{children}</p>; }

function ReferralCard({ referral }: { referral: DashboardData["referral"] }) {
  const copy = async () => { try { await navigator.clipboard.writeText(referral.url); toast.success("Referral link copied."); } catch { toast.error("Could not copy the referral link."); } };
  const share = async () => { if (!navigator.share) { await copy(); return; } try { await navigator.share({ title: "Join my network", text: "Register with my referral link.", url: referral.url }); } catch { /* Member dismissed the browser share sheet. */ } };
  return <Card className="overflow-hidden border-primary/20 bg-gradient-to-br from-primary/[0.10] via-card to-card"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Grow your network</p><h2 className="mt-1 text-xl font-bold tracking-tight">Your referral link</h2></div><div className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground"><Gift className="size-5" /></div></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Share your unique link with people you know. Attribution is applied only after a valid registration.</p><div className="mt-5 flex items-center gap-2 rounded-xl border bg-background/80 p-2 pl-3"><p className="min-w-0 flex-1 truncate font-mono text-xs text-muted-foreground" title={referral.url}>{referral.url}</p><Button size="icon" variant="ghost" aria-label="Copy referral link" onClick={() => void copy()}><Copy className="size-4" /></Button></div><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => void copy()}><Copy className="size-4" />Copy link</Button><Button size="sm" variant="outline" onClick={() => void share()}>Share</Button></div><div className="mt-6 grid grid-cols-2 border-t pt-4"><div><p className="text-xl font-bold">{referral.directReferrals}</p><p className="text-xs text-muted-foreground">Direct referrals</p></div><div className="border-l pl-4"><p className="text-xl font-bold">{referral.teamMembers}</p><p className="text-xs text-muted-foreground">Total team</p></div></div></CardContent></Card>;
}

function NotificationRow({ entry }: { entry: DashboardData["notifications"][number] }) { const content = <div className="flex gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg ${entry.read ? "bg-muted text-muted-foreground" : "bg-primary/10 text-primary"}`}><Bell className="size-4" /></div><div className="min-w-0"><p className="truncate text-sm font-medium">{entry.title}</p><p className="mt-0.5 line-clamp-2 text-xs leading-5 text-muted-foreground">{entry.body}</p><p className="mt-1 text-[11px] text-muted-foreground">{formatDateTime(entry.createdAt)}</p></div></div>; return entry.actionUrl ? <Link href={entry.actionUrl}>{content}</Link> : content; }

export function MemberDashboard() {
  const [data, setData] = useState<DashboardData | null>(null); const [failed, setFailed] = useState(false);
  const reduceMotion = useReducedMotion();
  const load = useCallback(async () => { try { setData(await getDashboard()); setFailed(false); } catch { setFailed(true); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  if (!data && !failed) return <SkeletonDashboard />;
  if (!data || failed) return <ErrorState title="Dashboard could not be loaded" description="Your account data is secure, but this view could not be refreshed." />;
  const earnings = data.charts.earnings.map((entry) => ({ label: entry.label, amount: graphAmount(entry.amountMinor) }));
  const breakdown = data.charts.commissionBreakdown.map((entry) => ({ ...entry, amount: graphAmount(entry.amountMinor) }));
  const hasEarnings = earnings.some((entry) => entry.amount > 0); const hasTeam = data.charts.teamGrowth.some((entry) => entry.members > 0);
  return <motion.div initial={reduceMotion ? false : "hidden"} animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: reduceMotion ? 0 : 0.04 } } }} className="space-y-6 pb-5">
    <motion.section variants={fade} className="relative overflow-hidden rounded-2xl border bg-gradient-to-br from-primary/[0.12] via-card to-card p-6 sm:p-8"><div className="absolute -right-12 -top-16 size-56 rounded-full bg-primary/[0.08] blur-2xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><Badge className="bg-primary text-primary-foreground">Member dashboard</Badge><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Good to see you, {data.member.firstName}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground sm:text-base">A clear view of your wallet, network, orders, and commission activity.</p></div><div className="rounded-xl border bg-background/70 px-4 py-3 backdrop-blur"><p className="text-xs font-medium text-muted-foreground">Member ID</p><p className="mt-1 font-mono text-sm font-semibold">{data.member.memberNumber}</p></div></div></motion.section>
    <motion.section variants={fade} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric icon={WalletCards} label="Wallet balance" value={formatCurrency(data.metrics.availableBalanceMinor, data.currency)} detail="Available to withdraw" /><Metric icon={TrendingUp} label="Total earnings" value={formatCurrency(data.metrics.lifetimeEarningsMinor, data.currency)} detail="Lifetime commissions" color="bg-emerald-500/10 text-emerald-700" /><Metric icon={Users} label="Direct referrals" value={String(data.metrics.directReferrals)} detail="Personally sponsored" color="bg-violet-500/10 text-violet-700" /><Metric icon={Network} label="Total team" value={String(data.metrics.totalTeam)} detail="Across every level" color="bg-sky-500/10 text-sky-700" /><Metric icon={CreditCard} label="Pending withdrawal" value={formatCurrency(data.metrics.pendingWithdrawalMinor, data.currency)} detail="Awaiting settlement" color="bg-amber-500/10 text-amber-700" /><Metric icon={ShoppingBag} label="Orders" value={String(data.metrics.orders)} detail="Orders from your account" color="bg-rose-500/10 text-rose-700" /></motion.section>
    <motion.section variants={fade} className="grid gap-6 xl:grid-cols-3"><Card className="min-w-0 xl:col-span-2"><Header title="Earnings over time" description="Approved commissions in the last six months" href="/member/wallet" action="Open wallet" /><CardContent className="h-72 min-h-72 min-w-0">{hasEarnings ? <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={216}><AreaChart data={earnings} margin={{ left: -15, right: 8, top: 8 }}><defs><linearGradient id="earnings-gradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={0.32} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }} /><Tooltip formatter={(value) => [formatCurrency(BigInt(Math.round(Number(value) * 100)), data.currency), "Earnings"]} contentStyle={{ borderRadius: 12, borderColor: "hsl(var(--border))" }} /><Area type="monotone" dataKey="amount" stroke="hsl(var(--primary))" strokeWidth={2.5} fill="url(#earnings-gradient)" /></AreaChart></ResponsiveContainer> : <EmptyState title="Your earnings will appear here" description="Eligible orders in your network will appear in this trend once commission is credited." />}</CardContent></Card><ReferralCard referral={data.referral} /></motion.section>
    <motion.section variants={fade} className="grid gap-6 lg:grid-cols-2"><Card className="min-w-0"><Header title="Commission mix" description="All approved commission credits" /><CardContent className="h-64 min-h-64 min-w-0">{hasEarnings ? <div className="flex h-full min-w-0 items-center gap-3"><ResponsiveContainer width="54%" height="100%" minWidth={0} minHeight={192}><PieChart><Pie data={breakdown} dataKey="amount" nameKey="name" innerRadius="60%" outerRadius="84%" paddingAngle={4}>{breakdown.map((entry, index) => <Cell key={entry.name} fill={index === 0 ? "hsl(var(--primary))" : "hsl(262 83% 58%)"} />)}</Pie><Tooltip formatter={(value) => formatCurrency(BigInt(Math.round(Number(value) * 100)), data.currency)} /></PieChart></ResponsiveContainer><div className="space-y-3">{breakdown.map((entry, index) => <div key={entry.name} className="flex items-center gap-2"><span className="size-2.5 rounded-full" style={{ background: index === 0 ? "hsl(var(--primary))" : "hsl(262 83% 58%)" }} /><div><p className="text-sm font-medium">{entry.name}</p><p className="text-xs text-muted-foreground">{formatCurrency(entry.amountMinor, data.currency)}</p></div></div>)}</div></div> : <EmptyState title="No commission mix yet" description="Direct and level commission totals appear after your first credited earnings." />}</CardContent></Card><Card className="min-w-0"><Header title="Team growth" description="New downline members by month" href="/member/team" action="View team" /><CardContent className="h-64 min-h-64 min-w-0">{hasTeam ? <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={192}><BarChart data={data.charts.teamGrowth} margin={{ left: -18, right: 8, top: 8 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }} /><Tooltip contentStyle={{ borderRadius: 12, borderColor: "hsl(var(--border))" }} /><Bar dataKey="members" name="New members" radius={[7, 7, 0, 0]} fill="hsl(var(--primary))" /></BarChart></ResponsiveContainer> : <EmptyState title="Build your first connection" description="Share your referral link to start seeing network growth here." action={<Button size="sm" asChild><Link href="/member/referral">Invite members</Link></Button>} />}</CardContent></Card></motion.section>
    <motion.section variants={fade} className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><Header title="Recent earnings" description="Latest approved commissions" href="/member/wallet" action="All activity" /><CardContent className="space-y-1">{data.recentEarnings.length ? data.recentEarnings.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div className="flex min-w-0 items-center gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-emerald-500/10 text-emerald-700"><TrendingUp className="size-4" /></div><div className="min-w-0"><p className="truncate text-sm font-medium">{entry.type === "DIRECT" ? "Direct referral commission" : `Level ${entry.level} commission`}</p><p className="truncate text-xs text-muted-foreground">From {entry.sourceMemberName} · {formatDateTime(entry.createdAt)}</p></div></div><p className="shrink-0 text-sm font-bold text-emerald-700">+{formatCurrency(entry.amountMinor, entry.currency)}</p></div>) : <NoActivity>No earnings have been credited yet. Keep sharing your referral link and eligible network orders will be reflected here.</NoActivity>}</CardContent></Card><Card><Header title="Notifications" description="Your latest account updates" /><CardContent className="space-y-1">{data.notifications.length ? data.notifications.map((entry) => <NotificationRow key={entry.id} entry={entry} />) : <NoActivity>Important account, order, and commission updates will appear here.</NoActivity>}</CardContent></Card></motion.section>
    <motion.section variants={fade} className="grid gap-6 xl:grid-cols-3"><Card><Header title="Recent referrals" href="/member/direct-referrals" action="View all" /><CardContent className="space-y-1">{data.recentReferrals.length ? data.recentReferrals.map((entry) => <div key={entry.memberNumber} className="flex items-center justify-between gap-3 rounded-xl p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{entry.name}</p><p className="text-xs text-muted-foreground">{entry.memberNumber} · Joined {formatDateTime(entry.joinedAt)}</p></div><Badge variant={entry.status === "ACTIVE" ? "success" : "secondary"}>{entry.status}</Badge></div>) : <NoActivity>No direct referrals yet. Your personalized link is ready to share above.</NoActivity>}</CardContent></Card><Card><Header title="Wallet activity" href="/member/wallet" action="Open wallet" /><CardContent className="space-y-1">{data.recentWalletTransactions.length ? data.recentWalletTransactions.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 rounded-xl p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{entry.type.replaceAll("_", " ")}</p><p className="truncate text-xs text-muted-foreground">{entry.description}</p></div><div className="shrink-0 text-right"><p className={entry.direction === "CREDIT" ? "text-sm font-bold text-emerald-700" : "text-sm font-bold"}>{entry.direction === "CREDIT" ? "+" : "−"}{formatCurrency(entry.amountMinor, data.currency)}</p><p className="text-[11px] text-muted-foreground">{formatDateTime(entry.createdAt)}</p></div></div>) : <NoActivity>Your immutable wallet entries will appear after your first commission or transaction.</NoActivity>}</CardContent></Card><Card><Header title="Recent orders" href="/member/orders" action="All orders" /><CardContent className="space-y-1">{data.recentOrders.length ? data.recentOrders.map((entry) => <Link key={entry.id} href={`/member/orders/${entry.id}`} className="flex items-center justify-between gap-3 rounded-xl p-3 transition-colors hover:bg-muted/60"><div><p className="text-sm font-medium">{entry.orderNumber}</p><p className="text-xs text-muted-foreground">{formatDateTime(entry.createdAt)} · {entry.paymentStatus}</p></div><div className="text-right"><p className="text-sm font-bold">{formatCurrency(entry.totalMinor, data.currency)}</p><Badge variant={entry.status === "PAID" || entry.status === "DELIVERED" ? "success" : "secondary"}>{entry.status}</Badge></div></Link>) : <NoActivity>When you checkout a product, its payment and fulfillment state will be visible here.</NoActivity>}</CardContent></Card></motion.section>
  </motion.div>;
}
