"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { ErrorState } from "@/components/shared/states";

type ProfileData = { user: { email: string; status: string }; profile: { memberNumber: string; referralCode: string; firstName: string; lastName: string; phone?: string; alternatePhone?: string; address?: { line1: string; line2?: string; city: string; state: string; postalCode: string; country: string } }; paymentDetails: { configured: boolean; accountLast4: string | null } };

export function ProfilePanel() {
  const [data, setData] = useState<ProfileData | null>(null); const [failed, setFailed] = useState(false); const [saving, setSaving] = useState(false); const [paymentOpen, setPaymentOpen] = useState(false);
  useEffect(() => { void fetch("/api/v1/members/me").then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<{ data: ProfileData }>; }).then((body) => setData(body.data)).catch(() => setFailed(true)); }, []);
  if (!data && !failed) return <div className="space-y-4"><Skeleton className="h-32" /><Skeleton className="h-80" /></div>;
  if (failed || !data) return <ErrorState />;
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const address = { line1: String(form.get("line1") ?? ""), line2: String(form.get("line2") ?? ""), city: String(form.get("city") ?? ""), state: String(form.get("state") ?? ""), postalCode: String(form.get("postalCode") ?? ""), country: String(form.get("country") ?? "") }; const response = await fetch("/api/v1/members/me", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ firstName: form.get("firstName"), lastName: form.get("lastName"), phone: form.get("phone"), alternatePhone: form.get("alternatePhone"), address: address.line1 || address.city ? address : null }) }); if (!response.ok) throw new Error(); toast.success("Profile updated."); } catch { toast.error("We could not save your profile. Check the address fields and try again."); } finally { setSaving(false); } };
  const savePayment = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const response = await fetch("/api/v1/members/me/payment-details", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ accountHolderName: form.get("accountHolderName"), bankName: form.get("bankName"), accountNumber: form.get("accountNumber"), ifscCode: form.get("ifscCode") }) }); if (!response.ok) throw new Error(); const body = await response.json() as { data: ProfileData["paymentDetails"] }; setData({ ...data, paymentDetails: body.data }); setPaymentOpen(false); toast.success("Payment details saved securely."); } catch { toast.error("We could not save payment details. Check the values and try again."); } finally { setSaving(false); } };
  const p = data.profile;
  return <div className="space-y-6"><Card><CardContent className="grid gap-4 p-6 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Member ID</p><p className="mt-1 font-semibold">{p.memberNumber}</p></div><div><p className="text-xs text-muted-foreground">Referral code</p><p className="mt-1 font-semibold">{p.referralCode}</p></div><div><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-1" variant={data.user.status === "ACTIVE" ? "success" : "warning"}>{data.user.status}</Badge></div></CardContent></Card><Card><CardHeader><CardTitle>Personal information</CardTitle><CardDescription>Your account email is {data.user.email}. Member ID and referral code cannot be changed.</CardDescription></CardHeader><CardContent><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><Input name="firstName" defaultValue={p.firstName} placeholder="First name" required /><Input name="lastName" defaultValue={p.lastName} placeholder="Last name" required /><Input name="phone" defaultValue={p.phone} placeholder="Phone" /><Input name="alternatePhone" defaultValue={p.alternatePhone} placeholder="Alternate phone" /><Input name="line1" defaultValue={p.address?.line1} placeholder="Address line 1" /><Input name="line2" defaultValue={p.address?.line2} placeholder="Address line 2" /><Input name="city" defaultValue={p.address?.city} placeholder="City" /><Input name="state" defaultValue={p.address?.state} placeholder="State" /><Input name="postalCode" defaultValue={p.address?.postalCode} placeholder="Postal code" /><Input name="country" defaultValue={p.address?.country} placeholder="Country code (IN)" maxLength={2} /><div className="md:col-span-2"><Button disabled={saving}>{saving ? "Saving…" : "Save profile"}</Button></div></form></CardContent></Card><Card><CardHeader><CardTitle>Bank and payment details</CardTitle><CardDescription>{data.paymentDetails.configured ? `An encrypted account ending in ${data.paymentDetails.accountLast4} is on file.` : "No payment details are stored."}</CardDescription></CardHeader><CardContent>{paymentOpen ? <form onSubmit={savePayment} className="grid gap-4 md:grid-cols-2"><Input name="accountHolderName" placeholder="Account holder name" required /><Input name="bankName" placeholder="Bank name" required /><Input name="accountNumber" placeholder="Account number" inputMode="numeric" required /><Input name="ifscCode" placeholder="IFSC code" className="uppercase" required /><div className="flex gap-2 md:col-span-2"><Button disabled={saving}>{saving ? "Saving…" : "Save encrypted details"}</Button><Button type="button" variant="outline" onClick={() => setPaymentOpen(false)}>Cancel</Button></div></form> : <Button variant="outline" onClick={() => setPaymentOpen(true)}>{data.paymentDetails.configured ? "Update payment details" : "Add payment details"}</Button>}</CardContent></Card></div>;
}
